chore: add Prettier action, cleanup workflow, add formatting instructions

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,31 +1,44 @@
 name: Go
 
 on:
-  push:
-    branches: [ master ]
   pull_request:
-    branches: [ master ]
+    types: [opened, synchronize, ready_for_review]
 
 jobs:
-
   build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Set up Go
-      uses: actions/setup-go@v5
-      with:
-        go-version: '1.22'
+      - name: Prettier
+        if: runner.os != 'Windows'
+        uses: rutajdash/prettier-cli-action@v1.0.2
+        with:
+          file_pattern: "**/*.{md,yml}"
 
-    - name: Build
-      run: go build -v ./...
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: stable
 
-    - name: Test
-      run: go test -v ./secretcache -coverprofile=coverage.out -covermode=atomic
-    
-    - name: Codecov
-      uses: codecov/codecov-action@v5
-      env:
-        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+      - name: Check Formatting
+        run: |
+          unformatted=$(gofmt -s -l .)
+          if [ -n "$unformatted" ]; then
+            echo "::error::The following files are not formatted properly:"
+            echo "$unformatted"
+            echo "Please run `gofmt -s -w .` to format your code."
+            exit 1
+          fi
 
+      - name: Build
+        run: go build -v ./...
+
+      - name: Test
+        run: go test -v ./secretcache -coverprofile=coverage.out -covermode=atomic
+
+      - name: Codecov
+        uses: codecov/codecov-action@v5
+        env:
+          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
